# Generated by Django 4.0.2 on 2022-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
