# Generated by Django 4.0.2 on 2022-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timein',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timeout',
            field=models.TimeField(),
        ),
    ]
