# Generated by Django 4.0.2 on 2022-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_admin_conferencerooms_payment_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
